---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetroot
  labels:
    app: beetroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beetroot
  template:
    metadata:
      labels:
        app: beetroot
    spec:
      containers:
      - name: beetroot
        image: ghcr.io/bjornarron/excercise2:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default
data:
  default: |
    events {
      worker_connections  1024;
    }
    http {
      server {
      listen 80;
      
      location / {
              proxy_pass http://10.107.240.24:8080/;
      }
      }
      include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          name: default
      volumes:
      - name: default
        configMap:
          name: default
          items:
          - key: default
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata: 
  name: beetroot-service
spec:
  type: ClusterIP
  clusterIP: 10.107.240.24
  selector: 
    app: beetroot
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
  name: exposing-nginx
spec:
  type: NodePort
  selector: 
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080